"""add expired links table

Revision ID: 80f65996ebf0
Revises: b3cfd1062883
Create Date: 2026-03-09 17:31:13.444667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f65996ebf0'
down_revision: Union[str, Sequence[str], None] = 'b3cfd1062883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expired_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('click_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expired_links_original_url'), 'expired_links', ['original_url'], unique=False)
    op.create_index(op.f('ix_expired_links_short_code'), 'expired_links', ['short_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expired_links_short_code'), table_name='expired_links')
    op.drop_index(op.f('ix_expired_links_original_url'), table_name='expired_links')
    op.drop_table('expired_links')
    # ### end Alembic commands ###
